api_platform:
  title: Fault-Tolerant University API
  version: 1.0.0
  mapping:
    paths: ['%kernel.project_dir%/src/Api/Resource']
  formats:
    json: ['application/json']
  patch_formats:
    json: ['application/merge-patch+json']
  docs_formats:
    jsonopenapi: ['application/vnd.openapi+json']
    html: ['text/html']
  defaults:
    denormalization_context:
      allow_extra_attributes: false
    pagination_items_per_page: 20
    pagination_maximum_items_per_page: 100
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
