---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: midterm-monitoring
spec:
  encryptedData:
    password: AgAdQ8rM/8x3Eu9a+PU4DuEmueBForuY9rQbC0ESlny7peWQ9mnZRBCRMOQcfeoZRyYafYtLwVnFRWNbZ7QJBy0dqcH9t2udSv7Jn4yA3BprhKNms45+DRZGpOb0fX2+2fYd6Lq37at1hwBxVmyp2QQBTc4ItMw9V1SRPMC6JnD2WGRVlJCr1eo85XA5BB7GX7FCVW17F3/YSTFbDtF8Qq333AZ/VL2SWeIqmGxX7EphD4/K5IGJAitHtADYy+YeDHYiHStwBNjOlyRdod2lejy80N8XWqODpeMaJFMIuelbYjmZ7r0zIF1ibwB47OUFllGM9LNM0H6YBZCdxowApxXVZelViqA52qAvaMmHPLHrjj7W0T/WRYkh0Q+g8Mu+gIimQGkxB8fo4nPHKSF1g/iGDk9xNf06tpuoyLxK73tr0AwkyK4hvGSBIq+ZYtRLUO/+1lHC+aZfDgFuTF3JJfoG1mrzdA7YPHY3qHteLTb0sc9V/kjz1FRfeOMlO8ddoPIlH7Gela7u5+4ab0hppYzWMAmqOIxnSdIA8WGWthdVXWaJUm0oORMNhWOI7TVQew+A+Cd/FSS/TdHBr+sgAgYmOpW5bWU2YI9bPMw937Z2eel3y1JkuCMdHTnecK3Sg8bSmF9kZya2/kR2JcywEgSmI8v1/gWCy9uYkqTM1SNovvucQuStDrl4YXrlHhE3LQUrINtOje0p9No+0N9dgQmF04EFvXzHg+5kWUf4lGAfXw==
  template:
    metadata:
      name: grafana-secret
      namespace: midterm-monitoring
    type: Opaque
