apiVersion: v1
kind: Namespace
metadata:
  name: midterm
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    # Keep namespaces (and their PVCs) if this Application is ever deleted.
    argocd.argoproj.io/sync-options: Delete=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: midterm-baseline
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    # Keep namespaces (and their PVCs) if this Application is ever deleted.
    argocd.argoproj.io/sync-options: Delete=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: midterm-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    # Keep namespaces (and their PVCs) if this Application is ever deleted.
    argocd.argoproj.io/sync-options: Delete=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: midterm-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    # Keep namespaces (and their PVCs) if this Application is ever deleted.
    argocd.argoproj.io/sync-options: Delete=false
